### ISSUE TITLE
Simple test doesn't work

### ISSUE THREAD

**Issue by pbreneman** [FirebirdSQL/jaybird#22]
See [http://www.controlpascal.com/firebird.htm](Firebird)

**Comment by mrotteveel** [comment]
Your problem looks like a support question, and we prefer those to be sent to the firebird-java mailinglist.

If you really think this is a bug, please be sure to provide all relevant information, for example I don't see a clear error or problem description on that link.

Some guesses for possible solutions/workarounds:

- When using from LibreOffice or OpenOffice, use the `jdbc:firebirdsql:oo:` prefix, not `jdbc:firebirdsql:`. The `jdbc:firebirdsql:oo` protocol uses some different options for LibreOffice/OpenOffice
- By default, Jaybird 4 will only connect with the Srp256 and Srp authentication protocols, but a default install of Firebird will only have a legacy_auth user setup. Make sure you created a Srp user, or alternatively, use specify connection property `authPlugins=Legacy_Auth`
- You are connecting to a database in the `Program Files` folder, depending on how Firebird was started, the process may not have read/write access here, which means it cannot connect (this can happen when Firebird is started as an application instead of as a Windows service).
- Jaybird 4 is in beta, please try with Jaybird 3.0.6 as well
