### ISSUE TITLE
No sense private constructor

### ISSUE THREAD

**Issue by maxrode** [FirebirdSQL/jaybird#28]
https://github.com/FirebirdSQL/jaybird/blob/0aa364cca7dde79c8e71f18a2173ca5a050aceeb/src/main/org/firebirdsql/event/FBEventManager.java#L85

Please can make FBEventManager(Connection connection) public, it's very no sense to make it private and create a static method "createFor" that call private constructor

**Comment by mrotteveel** [comment]
Thank you for the suggestion, but I'm not going to follow it up. This design is intentional, the static factory method `FBEventManager.createFor`  returns an instance of `EventManager` interface, and might return a different implementation of `EventManager` in the future. Additionally, I don't want to allow sub-classes of `FBEventManager` that use this constructor.
