### ISSUE TITLE
Return metadata for procedures inside packages

### ISSUE THREAD

**Issue by EPluribusUnum** [FirebirdSQL/jaybird#724]
Hi Mark!

`FBDatabaseMetaData.getProcedures()`
Currenty it's impossible to get metadata for package procedures. There should be a way to do it.

Split _procedureNamePattern_ on "." character and use first part as package filter is OK for me, but might broke others existing code as _procedureNamePattern_ is a regex, and "." is a valid regex character. Maybe use _catalog_ parameter for package name filtering? I think _catalog_ has a very loose definiton by JDBC.

Thank You!

**Comment by mrotteveel** [comment]
No, this is not possible, because that will break normal JDBC API expectations. 

Your first scheme would break for procedures that contain a period in their names. For example, `create procedure "part1.part2" ...` is perfectly valid, and needs to be retrievable with `getProcedures(null, null, "part1.part2"). As an aside, `procedureNamePattern` is not a regex, it is a `LIKE` pattern, where `.` has no special meaning (only `_`, `%` and `\_` and `\%` have special meaning).

You second scheme simply doesn't comply with the definition and usage of catalog in standard SQL and the JDBC specification (a catalog is something which contains one or more schemas, a schema is something which contains objects (tables, etc)). In those terms, for Firebird, a database is an unnamed catalog, which has one unnamed schema. In addition, it breaks with the normal rules and expectations for how - for example - `getProcedures(null, null, "%")` works (returning **all** stored procedures). And that normal tools following JDBC expectations might not be capable of correctly calling those stored procedures this way.

I will consider adding a `getPackages` method and `getPackageProcedures and `getPackageProcedureColumns`, but given I think the usefulness of this is pretty limited, I will consider that for some future version.

**Comment by EPluribusUnum** [comment]
That is strange, how other DB drivers handle this case?
Why do you think that getting the metadata is not so useful? A package is just a simple namespace separation, otherwise its a fully functional procedure.

**Comment by EPluribusUnum** [comment]
Maybe a connection string parameter which alters the `procedureNamePattern ` processing?

**Comment by mrotteveel** [comment]
As far as I'm aware, Oracle doesn't return packages from its DatabaseMetaData methods. I'm not aware of other DBMSes which have packages as such.

The reason I think it is not very useful, is because `DatabaseMetaData` is (primarily) intended for (standard) tools/libraries to gather data about a database (dynamic discovery of features and objects). Having DBMS specific extensions exposed has limited usefulness, because normal tools will not be able to use it if you add extra methods, or not use it correctly if you try to overload meaning of the standard methods in non-standard ways (which means things will break in subtle or not so subtle ways). And if it is for a Firebird/Jaybird specific tool, they might as well just query the metadata tables directly to obtain the non-standard information. And "normal" applications will likely not consult the database metadata at all, but instead simply *use* the stored procedures and packages they defined for themselves.

I expect such a feature will not see much use (extra methods), or cause me a lot of headaches when things break in unexpected ways (overload meaning of standard methods). I prefer to follow the JDBC specification when I can to avoid such headaches, so adding extra methods will have my preference, but given that will result in limited exposure and actual use, I think it is not very efficient use of my time to create such a feature.

**Comment by EPluribusUnum** [comment]
OK. Currently it's not a priority on my side. If thete is a pressure to handle, I'll do it with direct metadata SELECT.

(To clarify, I don't want to get the metadata of the package itself (eg list of procedures), but metadata for a procedure inside the package.)

**Comment by mrotteveel** [comment]
It looks like Oracle actually does the second scheme you suggested (overloading the meaning of catalog for getProcedures). I'll give this some thought to see if that is something that might be viable, maybe behind a connection property to enable it.

**Comment by mrotteveel** [comment]
Tentatively scheduled for Jaybird 6

**Comment by mrotteveel** [comment]
@EPluribusUnum Could you take a look at https://github.com/FirebirdSQL/jaybird/blob/master/devdoc/jdp/jdp-2023-09-use-catalog-as-package.adoc ?

**Comment by EPluribusUnum** [comment]
@mrotteveel , this looks fine to me.
