### ISSUE TITLE
Only one result set at a time/statement.

### ISSUE THREAD

**Issue by caxzan** [FirebirdSQL/jaybird#762]
When I am linking with a third-party software, the third-party software calls the data link of Firebird and executes an SQL statement. At this time, it returns an error statement: Only one result set at a time/statement, May I ask how to avoid this problem, or if it can be directly solved in Firebird's JAR.
![image](https://github.com/FirebirdSQL/jaybird/assets/17541369/323932fd-6ba8-4d35-b044-2b46a70d1cfe)

**Comment by mrotteveel** [comment]
Jaybird throws this exception because it already returned the result set (either as the return value of `executeQuery` or from a previous call to `getResultSet` for this execution of the statement. It does this because the JDBC API says _" This method should be called only once per result."_. However, looking at the API documentation, I'm not entirely sure that is the intended behaviour. I'll try to find out more.

Is this `weaver.conn.RecordSet` your own code?

**Comment by mrotteveel** [comment]
Looking at the JDBC spec, calling `getResultSet` multiple times or after the result set has been returned by `executeQuery` is not disallowed, it just recommends that it should not be done, as such no exception should be thrown.  Also, I looked at the PostgreSQL and Microsoft SQL Server JDBC driver implementations, and they return the existing result set without a fuss.

I'll make the necessary changes in Jaybird 6.

**Comment by mrotteveel** [comment]
Decided to backport this to Jaybird 5.0.5 as well, see #809

**Comment by caxzan** [comment]
ok&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FirebirdSQL/jaybird"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月14日(星期五) 下午3:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [FirebirdSQL/jaybird] Remove restriction to only allow calls to getResultSet if the result set was not returned yet (Issue #762)





 
Decided to backport this to Jaybird 5.0.5 as well, see #809
